version: "2.1"
services:
  db:
    image: mysql:5.6
    container_name: edx_rbac_demo.db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - devstack_default
    volumes:
      - edx_rbac_demo_mysql:/var/lib/mysql

  memcache:
    image: memcached:1.4.24
    container_name: edx_rbac_demo.memcache

  app:
    # Uncomment this line to use the official edx_rbac_demo base image
    image: openedx/edx_rbac_demo

    container_name: edx_rbac_demo.app
    volumes:
      - .:/edx/app/edx_rbac_demo/
    command: bash -c 'while true; do python /edx/app/edx_rbac_demo/manage.py runserver 0.0.0.0:8000; sleep 2; done'
    environment:
      DJANGO_SETTINGS_MODULE: edx_rbac_demo.settings.devstack
    ports:
      - "8000:8000" # TODO: change this to your port
    networks:
      - devstack_default
    stdin_open: true
    tty: true

networks:
  devstack_default:
    external: true

volumes:
  edx_rbac_demo_mysql:
 