version: "2.1"
services:
  db:
    image: mysql:5.6
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - devstack_default
    volumes:
      - edx_rbac_demo_mysql:/var/lib/mysql

  memcache:
    image: memcached:1.4.24
    container_name: memcache

  edx_rbac_demo:
    # Uncomment this line to use the official edx_rbac_demo base image
    image: openedx/edx_rbac_demo

    container_name: edx_rbac_demo
    volumes:
      - .:/edx/app/edx_rbac_demo/
    command: bash -c 'gunicorn --reload --workers=2 --name edx_rbac_demo -b :8000 -c /edx/app/edx_rbac_demo/edx_rbac_demo/docker_gunicorn_configuration.py --log-file - --max-requests=1000 edx_rbac_demo.wsgi:application'
    environment:
      DJANGO_SETTINGS_MODULE: edx_rbac_demo.settings.devstack
    ports:
      - "8000:8000" # TODO: change this to your port
    networks:
      - devstack_default

networks:
  devstack_default:
    external: true

volumes:
  edx_rbac_demo_mysql:
