""" Constants for the core app. """


class Status:
    """Health statuses."""
    OK = u"OK"
    UNAVAILABLE = u"UNAVAILABLE"

ENTERPRISE_LEARNER_SYSTEM_WIDE_ROLE = 'enterprise_learner'
ENTERPRISE_ADMIN_SYSTEM_WIDE_ROLE = 'enterprise_admin'
ENTERPRISE_ACCOUNT_LEARNER_FEATURE_ROLE = 'enterprise_account_learner'
ENTERPRISE_ACCOUNT_ADMIN_FEATURE_ROLE = 'enterprise_account_admin'

SYSTEM_TO_FEATURE_ROLE_MAPPING = {
    ENTERPRISE_LEARNER_SYSTEM_WIDE_ROLE: [ENTERPRISE_ACCOUNT_LEARNER_FEATURE_ROLE],
    ENTERPRISE_ADMIN_SYSTEM_WIDE_ROLE: [ENTERPRISE_ACCOUNT_ADMIN_FEATURE_ROLE],
}
